### ISSUE TITLE
Why is ListPeers potentially unsafe?

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/go-libp2p-kbucket#4]
The comment for `ListPeers` in `table.go` has

    // NOTE: This is potentially unsafe... use at your own risk

Why is `ListPeers` potentially unsafe?

**Comment by JustinDrake** [comment]
I am looking to use `ListPeers` in production. [Git blame](https://github.com/libp2p/go-libp2p-kbucket/commit/560a474777c069f76eaa8c1250560a77b89cc4cf) points the finger to @whyrusleeping :)

**Comment by whyrusleeping** [comment]
Hrm... i'm not sure why honestly. It appears to do proper locking.

**Comment by whyrusleeping** [comment]
Ah, it used to not be threadsafe, then @jbenet fixed it and didnt update the comment: https://github.com/libp2p/go-libp2p-kbucket/commit/b819b92ec4010102e05b0219c723e9cc4f6276e6
