### ISSUE TITLE
Error during go get: no Go files in...

### ISSUE THREAD

**Issue by GiraffeKey** [libp2p/go-libp2p-kbucket#94]
Hi, when I try to run `go get github.com/libp2p/go-libp2p-kbucket` I get the following message:

`../../libp2p/go-libp2p-kbucket/peerdiversity/filter.go:13:2:` no Go files in ~/go/src/github.com/libp2p/go-libp2p-asn-util`

Any idea what is causing this and how to fix it?

**Comment by Stebalien** [comment]
Please use go modules.

**Comment by aschmahmann** [comment]
This seems closed. Feel free to reopen if I'm mistaken.
